### ISSUE TITLE
Operator starts wrong job types

### ISSUE THREAD

**Issue by ccremer** [vshn/k8up#256] opened 2021-01-04 15:26 UTC
## Describe the bug

During testing the newest RC of the k8up operator running on test1, it's observed that the operator seems to start a prune pod instead of a backup pod when a backup schedule is changed so that the backup runs at a specific time. 

it's assumed this behavior happens because a prune hasn't previously completed successfully for this project. This prune pod then starts and fails to run because it is missing the AWS secret key in its env vars. This prune pod will then remain in crashloop backoff state for about 30 minutes due to the missing AWS secret key before it is marked as failed by the operator. After this prune job fails, no backup is attempted afterwards.

## Additional context

* specifically observed this behavior on both the `drupal-example-test1-master` and `drupal-example-test1-develop` environments.
* verified that the missing secret key does seem to exist in the `syn-backup` namespace's `global-bucket-credentials` secret, so this may be an issue with how the operator is creating that prune pod specification?
* As the logs show, the controller correctly parsed out the timeframe the prune should run, but it still tried to schedule a prune instead of a backup. This prune then failed, and the controller did not attempt to perform a backup.
* tried to remove the `prune` key in the schedule object, and a check was attempted instead of a backup, which still failed for the same reason. After removing both the `prune` and `check` keys, it was found that a backup was started and the pre backup pods ran through successfully, but the same issue with the missing AWS secret key still persists, causing that backup pod to crashloop.

## Logs

If applicable, add logs to help explain your problem.
```console
2020-12-31T17:18:09.973+0100	INFO	controllers.Schedule	registering schedule for	{"schedule": "drupal-example-test1-master/k8up-lagoon-backup-schedule", "type": "backup", "schedule": "19 * * * *"}
2020-12-31T17:18:09.973+0100	INFO	controllers.Schedule	registering schedule for	{"schedule": "drupal-example-test1-master/k8up-lagoon-backup-schedule", "type": "check", "schedule": "28 3 * * 0"}
2020-12-31T17:18:09.973+0100	INFO	controllers.Schedule	registering schedule for	{"schedule": "drupal-example-test1-master/k8up-lagoon-backup-schedule", "type": "prune", "schedule": "28 3 * * 6"}
2020-12-31T17:18:09.973+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "backup.appuio.ch", "reconcilerKind": "Schedule", "controller": "schedule", "name": "k8up-lagoon-backup-schedule", "namespace": "drupal-example-test1-master"}
2020-12-31T17:19:00.000+0100	INFO	controllers.Schedule	running schedule for	{"schedule": "drupal-example-test1-master/k8up-lagoon-backup-schedule", "jb": "prune"}
2020-12-31T17:19:00.026+0100	INFO	controllers.Prune	adding job to the queue	{"prune": "drupal-example-test1-master/prunejob-1609431540"}
2020-12-31T17:19:01.558+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "batch", "reconcilerKind": "Job", "controller": "job", "name": "prunejob-1609431540", "namespace": "drupal-example-test1-master"}
2020-12-31T17:19:01.558+0100	INFO	observer	new event on observed job	{"event": "create", "jobName": "drupal-example-test1-master/prunejob-1609431540"}
2020-12-31T17:19:01.565+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "backup.appuio.ch", "reconcilerKind": "Prune", "controller": "prune", "name": "prunejob-1609431540", "namespace": "drupal-example-test1-master"}
2020-12-31T17:19:01.610+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "batch", "reconcilerKind": "Job", "controller": "job", "name": "prunejob-1609431540", "namespace": "drupal-example-test1-master"}
2020-12-31T17:19:01.611+0100	INFO	observer	new event on observed job	{"event": "running", "jobName": "drupal-example-test1-master/prunejob-1609431540"}
2020-12-31T17:19:01.617+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "batch", "reconcilerKind": "Job", "controller": "job", "name": "prunejob-1609431540", "namespace": "drupal-example-test1-master"}
2020-12-31T17:19:01.617+0100	INFO	observer	new event on observed job	{"event": "running", "jobName": "drupal-example-test1-master/prunejob-1609431540"}
2020-12-31T17:25:04.553+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "batch", "reconcilerKind": "Job", "controller": "job", "name": "prunejob-1609431540", "namespace": "drupal-example-test1-master"}
2020-12-31T17:25:04.553+0100	INFO	observer	new event on observed job	{"event": "failed", "jobName": "drupal-example-test1-master/prunejob-1609431540"}
2020-12-31T17:25:04.553+0100	INFO	controllers.Prune	cleaning old job	{"prune": "drupal-example-test1-master/prunejob-1609431540", "namespace": "drupal-example-test1-master", "name": "prunejob-1609025280"}
2020-12-31T17:25:04.561+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "backup.appuio.ch", "reconcilerKind": "Prune", "controller": "prune", "name": "prunejob-1609025280", "namespace": "drupal-example-test1-master"}
2020-12-31T17:25:04.568+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "backup.appuio.ch", "reconcilerKind": "Prune", "controller": "prune", "name": "prunejob-1609431540", "namespace": "drupal-example-test1-master"}
2020-12-31T17:25:04.575+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "backup.appuio.ch", "reconcilerKind": "Prune", "controller": "prune", "name": "prunejob-1609431540", "namespace": "drupal-example-test1-master"}
2020-12-31T17:25:06.006+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "batch", "reconcilerKind": "Job", "controller": "job", "name": "prunejob-1609025280", "namespace": "drupal-example-test1-master"}
2020-12-31T17:25:06.006+0100	INFO	observer	new event on observed job	{"event": "delete", "jobName": "drupal-example-test1-master/prunejob-1609025280"}
2020-12-31T17:25:06.006+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "batch", "reconcilerKind": "Job", "controller": "job", "name": "prunejob-1609025280", "namespace": "drupal-example-test1-master"}
2020-12-31T17:25:06.006+0100	INFO	observer	deleting job from observer	{"jobName": "drupal-example-test1-master/prunejob-1609025280"}
2020-12-31T17:25:06.027+0100	DEBUG	controller	Successfully Reconciled	{"reconcilerGroup": "backup.appuio.ch", "reconcilerKind": "Prune", "controller": "prune", "name": "prunejob-1609025280", "namespace": "drupal-example-test1-master"}
```

## To Reproduce

1. Specs
```yaml
apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  creationTimestamp: "2020-09-01T20:52:05Z"
  finalizers:
  - k8up.syn.tools/schedule
  name: k8up-lagoon-backup-schedule
  namespace: drupal-example-test1-master
spec:
  backend:
    repoPasswordSecretRef:
      key: repo-pw
      name: baas-repo-pw
    s3:
      bucket: baas-drupal-example-test1
  backup:
    resources: {}
    schedule: 28 0 * * *
  check:
    resources: {}
    schedule: 28 3 * * 0
  prune:
    resources: {}
    retention:
      keepDaily: 7
      keepWeekly: 6
    schedule: 28 3 * * 6
  resourceRequirementsTemplate: {}

```
2. Commands
```bash

```

## Environment (please complete the following information):

- Image Version: v1.0.0-rc2
- K8s Version: v1.18
- K8s Distribution: Rancher

**Comment by cdchris12** [comment] 2021-01-04 18:25
It's important to note that there are two distinct issues here:

1. The operator starts prune pods instead of check pods or backup pods, regardless of which type should be ran
    - Any time a `prune` key exists in the schedule object, a prune is always attempted first.
2. All pods created by the operator are missing their AWS secret credentials
    - This affects all backup, check, and prune pods created by the operator equally.
    - Since prebackup pods do not actually send data to S3 directly, they are unaffected.

**Comment by ccremer** [comment] 2021-01-05 16:04
Thanks for clarifying. We have identified the AWS secret issue already in the meantime, so we can focus this issue on the job type.

**Comment by cimnine** [comment] 2021-01-11 16:16
> The operator starts prune pods instead of check pods or backup pods, regardless of which type should be ran
> * Any time a prune key exists in the schedule object, a prune is always attempted first.

I was not yet able to reproduce this locally. We have decided to proceed with releasing rc3 and re-evaluate this in said version.

**Comment by cimnine** [comment] 2021-01-18 08:57
> The operator starts prune pods instead of check pods or backup pods, regardless of which type should be ran

I was not able to reproduce and observe this problem with v1.0.0-rc3 locally, neither on the test cluster. @cdchris12 is this still anything you experience/observe? Can you provide additional guidance?

**Comment by cdchris12** [comment] 2021-01-18 19:10
I've tested `v1.0.0-rc3` extensively, and I cannot replicate this issue anymore. I think we can call this case closed :)

**Comment by tobru** [comment] 2021-01-19 07:22
Thanks @cdchris12 for reporting back. Let's close this issue for now. If you encounter this problem again, just open a new issue.

**Closed by tobru** 2021-01-19 07:22 UTC
Labels: bug
