### ISSUE TITLE
pvc with RWO mode can't be backup, if the pvc mounting in other node.

### ISSUE THREAD

**Issue by jpsn123** [vshn/k8up#502] opened 2021-09-15 07:15 UTC
## Summary

**As** "cloud engineer"\
**I want** "backup job can create on node whice the pod using pvc running.  the job just mount pvcs who be mounted into same node. "\
**So that** "the pvc with RWO mode can be backup in multi-node k8s cluster. (RWO's pvc can be muti-mounted if in same node.)"

## Context

My cluster is composed of three nodes. When I created a backup job, I found that it was not successfully created because the job mounted multiple PVCs, which were mounted to different nodes, because the POD ran randomly on different nodes. but PVCs are all RWO mode, so pod creation was blocked.

## Implementation Ideas

* RWO's pvc can be muti-mounted if in same node.
* find the node whice pvc is mounted, according the pod `pod.status.hostIP` using the pvc.
* create job mount the pvc, just allow the job run on the same node.

**Comment by tobru** [comment] 2021-09-15 07:46
This is a duplicate of #319.

**Closed by tobru** 2021-09-15 07:46 UTC
Labels: enhancement
