### ISSUE TITLE
Create a consistent developer experience

### ISSUE THREAD

**Issue by bittner** [vshn/k8up#101] opened 2020-05-12 01:11 UTC
In a recent workshop we had with APPUiO customers, the developers seemed irritated about having to use [restic](https://restic.net/) to list historic snapshots of their backups and/or do a manual restore. Later, as we mentioned the `Archive` object, we explained that by design we don't use restic for long-term storage of backups.

Also, the customers - who had specifically asked for a demo of backing up and restoring (Postgres) database data - seemed irritated about the fact that k8up simply backs up data from the file system volume instead of specifically "doing database backups".

Apparently, from the perspective of an application developer, this seems like an inconsistent tool chain and/or user experience. That makes it harder to "sell" the promise that k8up makes backups and restore real simple.

Proposed Solution
---------------

* We should provide an **abstraction layer** wherever there is something else then "just k8up", for any interaction related to backup and restore data.
* In abstract terms, application developers should always **interact with "k8up"**, never with the tools or interfaces directly of the technologies that are used to implement k8up.
* In addition, the notion of **application-aware backups** should be more easily accessible; maybe by avoiding the need to specify the actual backup/restore commands for well-known applications.

In practical terms, this could be by

1. providing a `k8up` CLI (with an idiomatic, self-explanatory interface), and/or
1. providing means that make it easy to create a user interface to interact with creating backups & restore data for applications from within a web application (e.g. our Customer Portal)

**Comment by bittner** [comment] 2020-05-12 01:20
Related internal ticket: APPU-1902

**Comment by Kidswiss** [comment] 2020-05-12 05:58
Also relates to: APPU-1370 -> backup command templates for well known apps.

> Also, the customers - who had specifically asked for a demo of backing up and restoring (Postgres) database data - seemed irritated about the fact that k8up simply backs up data from the file system volume instead of specifically "doing database backups".

That's not quite correct, we demonstrated the backup command ability, although for MySQL. The issue is more with the restore that needs quite a lot of manual steps for this. There may not be a "one size fits them all" for restores as they can vary quite a bit depending on the use case.

**Comment by tobru** [comment] 2020-12-22 10:27
We close this issue and will recreate more actionable issues to tackle the UX with K8up.

**Closed by tobru** 2020-12-22 10:27 UTC
Labels: enhancement

**Comment by tobru** [comment] 2021-01-22 08:58
Related to https://github.com/vshn/k8up/issues/325
